twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        project_dir: '%kernel.project_dir%'

when@test:
    twig:
        strict_variables: true
    
    
