<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250327142801 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE affectation_hebergement DROP FOREIGN KEY FK_AFFECTATION_UTILISATEUR');
        $this->addSql('ALTER TABLE affectation_hebergement CHANGE DATE_DEBUT date_debut DATE NOT NULL, CHANGE DATE_FIN date_fin DATE NOT NULL');
        $this->addSql('DROP INDEX fk_affectation_utilisateur ON affectation_hebergement');
        $this->addSql('CREATE INDEX IDX_CD6257E9F6170F81 ON affectation_hebergement (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE affectation_hebergement ADD CONSTRAINT FK_AFFECTATION_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('DROP INDEX `primary` ON affectation_interview');
        $this->addSql('ALTER TABLE affectation_interview DROP FOREIGN KEY FK_ASSOCIATION_19');
        $this->addSql('ALTER TABLE affectation_interview CHANGE DATE_AFFECTATION_INTERVIEW date_affectation_interview DATETIME NOT NULL');
        $this->addSql('ALTER TABLE affectation_interview ADD PRIMARY KEY (ID_INTERVIEW, ID_UTILISATEUR)');
        $this->addSql('DROP INDEX fk_association_19 ON affectation_interview');
        $this->addSql('CREATE INDEX IDX_709641839547CAD3 ON affectation_interview (ID_INTERVIEW)');
        $this->addSql('ALTER TABLE affectation_interview ADD CONSTRAINT FK_ASSOCIATION_19 FOREIGN KEY (ID_INTERVIEW) REFERENCES interview (ID_INTERVIEW) ON DELETE CASCADE');
        $this->addSql('DROP INDEX `primary` ON affectation_interview1');
        $this->addSql('ALTER TABLE affectation_interview1 DROP FOREIGN KEY FK_idInterview');
        $this->addSql('ALTER TABLE affectation_interview1 CHANGE DATE_AFFECTATION_INTERVIEW date_affectation_interview DATE NOT NULL');
        $this->addSql('ALTER TABLE affectation_interview1 ADD PRIMARY KEY (ID_INTERVIEW, ID_UTILISATEUR)');
        $this->addSql('DROP INDEX fk_idinterview ON affectation_interview1');
        $this->addSql('CREATE INDEX IDX_F71DAB6C9547CAD3 ON affectation_interview1 (ID_INTERVIEW)');
        $this->addSql('ALTER TABLE affectation_interview1 ADD CONSTRAINT FK_idInterview FOREIGN KEY (ID_INTERVIEW) REFERENCES interview (ID_INTERVIEW) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branche_entreprise DROP FOREIGN KEY FK_ASSOCIATION_21');
        $this->addSql('ALTER TABLE branche_entreprise DROP FOREIGN KEY FK_BRANCHE');
        $this->addSql('ALTER TABLE branche_entreprise CHANGE ID_BRANCHE id_branche INT NOT NULL, CHANGE ID_ENTREPRISE ID_ENTREPRISE INT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE LOCALISATION_BRANCHE localisation_branche LONGTEXT NOT NULL, CHANGE EMAIL_BRANCHE email_branche LONGTEXT NOT NULL, CHANGE CONTACT_BRANCHE contact_branche VARCHAR(15) NOT NULL, CHANGE NOMBRE_EMPLOYE nombre_employe INT NOT NULL, CHANGE RESPONSABLE_BRANCHE responsable_branche LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX fk_branche ON branche_entreprise');
        $this->addSql('CREATE INDEX IDX_1C807087843F785 ON branche_entreprise (ID_ENTREPRISE)');
        $this->addSql('DROP INDEX fk_association_21 ON branche_entreprise');
        $this->addSql('CREATE INDEX IDX_1C807087F6170F81 ON branche_entreprise (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE branche_entreprise ADD CONSTRAINT FK_ASSOCIATION_21 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branche_entreprise ADD CONSTRAINT FK_BRANCHE FOREIGN KEY (ID_ENTREPRISE) REFERENCES entreprise (ID_ENTREPRISE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_CANDIDATURE_UTILISATEUR');
        $this->addSql('ALTER TABLE candidature CHANGE ID_CANDIDATURE id_candidature INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE DATE_CANDIDATURE date_candidature DATE NOT NULL, CHANGE STATUT_CANDIDATURE statut_candidature VARCHAR(255) NOT NULL, CHANGE CV cv VARCHAR(65535) NOT NULL');
        $this->addSql('DROP INDEX fk_candidature_utilisateur ON candidature');
        $this->addSql('CREATE INDEX IDX_E33BD3B8F6170F81 ON candidature (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_CANDIDATURE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire_publication DROP FOREIGN KEY FK_COMMENTAIRE_UTILISATEUR');
        $this->addSql('ALTER TABLE commentaire_publication DROP FOREIGN KEY FK_COMMENTAIRE_PUBLICATION');
        $this->addSql('ALTER TABLE commentaire_publication DROP FOREIGN KEY FK_COMMENTAIRE_REPONSE');
        $this->addSql('ALTER TABLE commentaire_publication CHANGE ID_COMMENTAIRE id_commentaire INT NOT NULL, CHANGE ID_PUBLICATION ID_PUBLICATION INT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE CONTENU contenu LONGTEXT NOT NULL, CHANGE DATE_COMMENTAIRE date_commentaire DATETIME NOT NULL');
        $this->addSql('DROP INDEX fk_commentaire_publication ON commentaire_publication');
        $this->addSql('CREATE INDEX IDX_423CD66B44370B4B ON commentaire_publication (ID_PUBLICATION)');
        $this->addSql('DROP INDEX fk_commentaire_utilisateur ON commentaire_publication');
        $this->addSql('CREATE INDEX IDX_423CD66BF6170F81 ON commentaire_publication (ID_UTILISATEUR)');
        $this->addSql('DROP INDEX idx_reponse ON commentaire_publication');
        $this->addSql('CREATE INDEX IDX_423CD66B73C208DE ON commentaire_publication (ID_REPONSE)');
        $this->addSql('ALTER TABLE commentaire_publication ADD CONSTRAINT FK_COMMENTAIRE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire_publication ADD CONSTRAINT FK_COMMENTAIRE_PUBLICATION FOREIGN KEY (ID_PUBLICATION) REFERENCES publication (ID_PUBLICATION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire_publication ADD CONSTRAINT FK_COMMENTAIRE_REPONSE FOREIGN KEY (ID_REPONSE) REFERENCES commentaire_publication (ID_COMMENTAIRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department_entreprise DROP FOREIGN KEY FK_CONTENI');
        $this->addSql('ALTER TABLE department_entreprise CHANGE ID_DEPARTEMENT id_departement INT NOT NULL, CHANGE ID_ENTREPRISE ID_ENTREPRISE INT DEFAULT NULL, CHANGE NOM_DEPARTEMENT nom_departement LONGTEXT NOT NULL, CHANGE DESCRIPTION_DEPARTEMENT description_departement LONGTEXT NOT NULL, CHANGE RESPONSABLE_DEPARTEMENT responsable_departement LONGTEXT NOT NULL, CHANGE NBR_EMPLOYE_DEPARTEMENT nbr_employe_departement INT NOT NULL');
        $this->addSql('DROP INDEX fk_conteni ON department_entreprise');
        $this->addSql('CREATE INDEX IDX_9F10F68C843F785 ON department_entreprise (ID_ENTREPRISE)');
        $this->addSql('ALTER TABLE department_entreprise ADD CONSTRAINT FK_CONTENI FOREIGN KEY (ID_ENTREPRISE) REFERENCES entreprise (ID_ENTREPRISE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE entreprise CHANGE ID_ENTREPRISE id_entreprise INT NOT NULL, CHANGE NOM_ENTREPRISE nom_entreprise LONGTEXT NOT NULL, CHANGE DESCRIPTION_ENTREPRISE description_entreprise LONGTEXT NOT NULL, CHANGE LOGO_ENTREPRISE logo_entreprise VARCHAR(255) NOT NULL, CHANGE URL_ENTREPRISE url_entreprise LONGTEXT NOT NULL, CHANGE SECTEUR_ENTREPRISE secteur_entreprise LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE hebergement DROP FOREIGN KEY FK_ASSOCIATION_14');
        $this->addSql('ALTER TABLE hebergement CHANGE ID_HEBERGEMENT id_hebergement INT NOT NULL, CHANGE ID_PARTENARIAT ID_PARTENARIAT INT DEFAULT NULL, CHANGE NOM_HEBERGEMENT nom_hebergement VARCHAR(255) NOT NULL, CHANGE ADRESSE_HEBERGEMENT adresse_hebergement VARCHAR(255) NOT NULL, CHANGE TYPE_HEBERGEMENT type_hebergement VARCHAR(255) NOT NULL, CHANGE DESCRIPTION_HEBERGEMENT description_hebergement LONGTEXT NOT NULL, CHANGE NBR_NUITE_HEBERGEMENT nbr_nuite_hebergement INT NOT NULL, CHANGE DISPONIBILITE_HEBERGEMENT disponibilite_hebergement TINYINT(1) NOT NULL, CHANGE LOCALISATION_HEBERGEMENT localisation_hebergement VARCHAR(255) NOT NULL, CHANGE PRIX_HEBERGEMENT prix_hebergement DOUBLE PRECISION NOT NULL');
        $this->addSql('DROP INDEX fk_association_14 ON hebergement');
        $this->addSql('CREATE INDEX IDX_4852DD9C5458B0B4 ON hebergement (ID_PARTENARIAT)');
        $this->addSql('ALTER TABLE hebergement ADD CONSTRAINT FK_ASSOCIATION_14 FOREIGN KEY (ID_PARTENARIAT) REFERENCES partenariat (ID_PARTENARIAT) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE historique_candidature DROP FOREIGN KEY FK_HISTORIQUE_CANDIDATURE');
        $this->addSql('ALTER TABLE historique_candidature CHANGE ID_HISTORIQUE id_historique INT NOT NULL, CHANGE ID_CANDIDATURE ID_CANDIDATURE INT DEFAULT NULL, CHANGE STATUT_AVANT statut_avant VARCHAR(255) NOT NULL, CHANGE STATUT_APRES statut_apres VARCHAR(255) NOT NULL, CHANGE DATE_MODIFICATION date_modification DATETIME NOT NULL');
        $this->addSql('DROP INDEX fk_historique_candidature ON historique_candidature');
        $this->addSql('CREATE INDEX IDX_3A95DDDE830BF8A ON historique_candidature (ID_CANDIDATURE)');
        $this->addSql('ALTER TABLE historique_candidature ADD CONSTRAINT FK_HISTORIQUE_CANDIDATURE FOREIGN KEY (ID_CANDIDATURE) REFERENCES candidature (ID_CANDIDATURE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_ASSOCIATION_20');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_INTERVIEW_UTILISATEUR');
        $this->addSql('ALTER TABLE interview CHANGE ID_INTERVIEW id_interview INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE ID_OFFRE ID_OFFRE INT DEFAULT NULL, CHANGE titre_offre titre_offre LONGTEXT NOT NULL, CHANGE nom_utilisateur nom_utilisateur VARCHAR(100) NOT NULL, CHANGE prenom_utilisateur prenom_utilisateur VARCHAR(100) NOT NULL, CHANGE DATE_INTERVIEW date_interview DATE NOT NULL, CHANGE TYPE_INTERVIEW type_interview VARCHAR(255) NOT NULL, CHANGE lien_Meet lien_meet VARCHAR(255) NOT NULL, CHANGE localisation localisation VARCHAR(255) NOT NULL, CHANGE time_Interview time_interview VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX fk_interview_utilisateur ON interview');
        $this->addSql('CREATE INDEX IDX_CF1D3C34F6170F81 ON interview (ID_UTILISATEUR)');
        $this->addSql('DROP INDEX fk_association_20 ON interview');
        $this->addSql('CREATE INDEX IDX_CF1D3C34809C5E25 ON interview (ID_OFFRE)');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_ASSOCIATION_20 FOREIGN KEY (ID_OFFRE) REFERENCES offre (ID_OFFRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_INTERVIEW_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offre DROP FOREIGN KEY FK_ASSOCIATION_13');
        $this->addSql('ALTER TABLE offre DROP FOREIGN KEY FK_offre_entreprise');
        $this->addSql('ALTER TABLE offre CHANGE ID_OFFRE id_offre INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE TITRE_OFFRE titre_offre LONGTEXT NOT NULL, CHANGE DESCRIPTION_OFFRE description_offre LONGTEXT NOT NULL, CHANGE SALAIRE_OFFRE salaire_offre DOUBLE PRECISION NOT NULL, CHANGE LOCALISATION_OFFRE localisation_offre LONGTEXT NOT NULL, CHANGE EMAIL_RH email_rh LONGTEXT NOT NULL, CHANGE ID_ENTREPRISE ID_ENTREPRISE INT DEFAULT NULL, CHANGE TYPE_CONTRAT type_contrat LONGTEXT NOT NULL, CHANGE DATE_LIMITE date_limite DATE NOT NULL');
        $this->addSql('DROP INDEX fk_association_13 ON offre');
        $this->addSql('CREATE INDEX IDX_AF86866FF6170F81 ON offre (ID_UTILISATEUR)');
        $this->addSql('DROP INDEX fk_offre_entreprise ON offre');
        $this->addSql('CREATE INDEX IDX_AF86866F843F785 ON offre (ID_ENTREPRISE)');
        $this->addSql('ALTER TABLE offre ADD CONSTRAINT FK_ASSOCIATION_13 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offre ADD CONSTRAINT FK_offre_entreprise FOREIGN KEY (ID_ENTREPRISE) REFERENCES entreprise (ID_ENTREPRISE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE partenariat DROP FOREIGN KEY FK_ASSOCIATION_23');
        $this->addSql('ALTER TABLE partenariat CHANGE ID_PARTENARIAT id_partenariat INT NOT NULL, CHANGE NOM_PARTENARIAT nom_partenariat VARCHAR(255) NOT NULL, CHANGE ADRESSE_PARTENARIAT adresse_partenariat VARCHAR(255) NOT NULL, CHANGE ID_BRANCHE ID_BRANCHE INT DEFAULT NULL, CHANGE NUM_TEL_PARTENARIAT num_tel_partenariat VARCHAR(15) NOT NULL');
        $this->addSql('DROP INDEX fk_association_23 ON partenariat');
        $this->addSql('CREATE INDEX IDX_BF53DC864E1D27AD ON partenariat (ID_BRANCHE)');
        $this->addSql('ALTER TABLE partenariat ADD CONSTRAINT FK_ASSOCIATION_23 FOREIGN KEY (ID_BRANCHE) REFERENCES branche_entreprise (ID_BRANCHE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_PROPOSER');
        $this->addSql('ALTER TABLE projet CHANGE ID_PROJET id_projet INT NOT NULL, CHANGE ID_OFFRE ID_OFFRE INT DEFAULT NULL, CHANGE TITRE_PROJET titre_projet LONGTEXT NOT NULL, CHANGE DESCRIPTION_PROJET description_projet LONGTEXT NOT NULL, CHANGE DATE_DEBUT date_debut DATE NOT NULL, CHANGE DATE_FIN date_fin DATE NOT NULL');
        $this->addSql('DROP INDEX fk_proposer ON projet');
        $this->addSql('CREATE INDEX IDX_50159CA9809C5E25 ON projet (ID_OFFRE)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_PROPOSER FOREIGN KEY (ID_OFFRE) REFERENCES offre (ID_OFFRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publication DROP FOREIGN KEY FK_ASSOCIATION_17');
        $this->addSql('ALTER TABLE publication CHANGE ID_PUBLICATION id_publication INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE CONTENU contenu LONGTEXT NOT NULL, CHANGE DATE_PUBLICATION date_publication DATETIME NOT NULL');
        $this->addSql('DROP INDEX fk_association_17 ON publication');
        $this->addSql('CREATE INDEX IDX_AF3C6779F6170F81 ON publication (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_ASSOCIATION_17 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY FK_ASSOCIATION_11');
        $this->addSql('ALTER TABLE reclamation CHANGE ID_RECLAMATION id_reclamation INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE DATE_RECLAMATION date_reclamation DATE NOT NULL, CHANGE TEXTE_RECLAMATION texte_reclamation LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX fk_association_11 ON reclamation');
        $this->addSql('CREATE INDEX IDX_CE606404F6170F81 ON reclamation (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_ASSOCIATION_11 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE repondre DROP FOREIGN KEY FK_REPONDRE2');
        $this->addSql('ALTER TABLE repondre DROP FOREIGN KEY FK_REPONDRE3');
        $this->addSql('DROP INDEX fk_repondre2 ON repondre');
        $this->addSql('CREATE INDEX IDX_F66FAAF48CFB048E ON repondre (ID_COMMENTAIRE)');
        $this->addSql('DROP INDEX fk_repondre3 ON repondre');
        $this->addSql('CREATE INDEX IDX_F66FAAF4F6170F81 ON repondre (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE repondre ADD CONSTRAINT FK_REPONDRE2 FOREIGN KEY (ID_COMMENTAIRE) REFERENCES commentaire_publication (ID_COMMENTAIRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE repondre ADD CONSTRAINT FK_REPONDRE3 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse_commentaire_publication CHANGE ID_REPONSE_COMMENTAIRE id_reponse_commentaire INT NOT NULL, CHANGE CONTENU_REPONSE_COMMENTAIRE_PUBLICATION contenu_reponse_commentaire_publication LONGTEXT NOT NULL, CHANGE DATE_REPONSE_COMMENTAIRE_PUBLICATION date_reponse_commentaire_publication DATE NOT NULL');
        $this->addSql('ALTER TABLE reponse_reclamation DROP FOREIGN KEY FK_ASSOCIATION_18');
        $this->addSql('ALTER TABLE reponse_reclamation CHANGE ID_REPONSE id_reponse INT NOT NULL, CHANGE ID_RECLAMATION ID_RECLAMATION INT DEFAULT NULL, CHANGE DATE_REPONSE date_reponse DATE NOT NULL, CHANGE TEXTE_REPONSE texte_reponse LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX fk_association_18 ON reponse_reclamation');
        $this->addSql('CREATE INDEX IDX_C7CB5101256B0836 ON reponse_reclamation (ID_RECLAMATION)');
        $this->addSql('ALTER TABLE reponse_reclamation ADD CONSTRAINT FK_ASSOCIATION_18 FOREIGN KEY (ID_RECLAMATION) REFERENCES reclamation (ID_RECLAMATION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE test_technique DROP FOREIGN KEY FK_ASSOCIATION_16');
        $this->addSql('ALTER TABLE test_technique CHANGE ID_TEST_TECHNIQUE id_test_technique INT NOT NULL, CHANGE ID_INTERVIEW ID_INTERVIEW INT DEFAULT NULL, CHANGE TITRE_TEST_TECHNIQUE titre_test_technique VARCHAR(255) NOT NULL, CHANGE DESCRIPTION_TEST_TECHNIQUE description_test_technique VARCHAR(255) NOT NULL, CHANGE DUREE_TEST_TECHNIQUE duree_test_technique INT NOT NULL, CHANGE STATUT_TEST_TECHNIQUE statut_test_technique VARCHAR(255) NOT NULL, CHANGE DATE_CREATION_TEST_TECHNIQUE date_creation_test_technique DATETIME NOT NULL, CHANGE questions questions LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX fk_association_16 ON test_technique');
        $this->addSql('CREATE INDEX IDX_55A60F8B9547CAD3 ON test_technique (ID_INTERVIEW)');
        $this->addSql('ALTER TABLE test_technique ADD CONSTRAINT FK_ASSOCIATION_16 FOREIGN KEY (ID_INTERVIEW) REFERENCES interview (ID_INTERVIEW) ON DELETE CASCADE');
        $this->addSql('DROP INDEX EMAIL_UTILISATEUR ON utilisateur');
        $this->addSql('ALTER TABLE utilisateur CHANGE ID_UTILISATEUR id_utilisateur INT NOT NULL, CHANGE NOM_UTILISATEUR nom_utilisateur VARCHAR(100) NOT NULL, CHANGE PRENOM_UTILISATEUR prenom_utilisateur VARCHAR(100) NOT NULL, CHANGE AGE_UTILISATEUR age_utilisateur INT NOT NULL, CHANGE EMAIL_UTILISATEUR email_utilisateur VARCHAR(255) NOT NULL, CHANGE MOT_DE_PASSE_UTILISATEUR mot_de_passe_utilisateur VARCHAR(255) NOT NULL, CHANGE ROLE role VARCHAR(255) NOT NULL, CHANGE reset_token reset_token VARCHAR(255) NOT NULL, CHANGE profile_picture_url profile_picture_url VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE affectation_hebergement DROP FOREIGN KEY FK_CD6257E9F6170F81');
        $this->addSql('ALTER TABLE affectation_hebergement CHANGE date_debut DATE_DEBUT DATE DEFAULT NULL, CHANGE date_fin DATE_FIN DATE DEFAULT NULL');
        $this->addSql('DROP INDEX idx_cd6257e9f6170f81 ON affectation_hebergement');
        $this->addSql('CREATE INDEX FK_AFFECTATION_UTILISATEUR ON affectation_hebergement (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE affectation_hebergement ADD CONSTRAINT FK_CD6257E9F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('DROP INDEX `PRIMARY` ON affectation_interview');
        $this->addSql('ALTER TABLE affectation_interview DROP FOREIGN KEY FK_709641839547CAD3');
        $this->addSql('ALTER TABLE affectation_interview CHANGE date_affectation_interview DATE_AFFECTATION_INTERVIEW DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE affectation_interview ADD PRIMARY KEY (ID_UTILISATEUR, ID_INTERVIEW)');
        $this->addSql('DROP INDEX idx_709641839547cad3 ON affectation_interview');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_19 ON affectation_interview (ID_INTERVIEW)');
        $this->addSql('ALTER TABLE affectation_interview ADD CONSTRAINT FK_709641839547CAD3 FOREIGN KEY (ID_INTERVIEW) REFERENCES interview (ID_INTERVIEW) ON DELETE CASCADE');
        $this->addSql('DROP INDEX `PRIMARY` ON affectation_interview1');
        $this->addSql('ALTER TABLE affectation_interview1 DROP FOREIGN KEY FK_F71DAB6C9547CAD3');
        $this->addSql('ALTER TABLE affectation_interview1 CHANGE date_affectation_interview DATE_AFFECTATION_INTERVIEW DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE affectation_interview1 ADD PRIMARY KEY (ID_UTILISATEUR, ID_INTERVIEW)');
        $this->addSql('DROP INDEX idx_f71dab6c9547cad3 ON affectation_interview1');
        $this->addSql('CREATE INDEX FK_idInterview ON affectation_interview1 (ID_INTERVIEW)');
        $this->addSql('ALTER TABLE affectation_interview1 ADD CONSTRAINT FK_F71DAB6C9547CAD3 FOREIGN KEY (ID_INTERVIEW) REFERENCES interview (ID_INTERVIEW) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branche_entreprise DROP FOREIGN KEY FK_1C807087843F785');
        $this->addSql('ALTER TABLE branche_entreprise DROP FOREIGN KEY FK_1C807087F6170F81');
        $this->addSql('ALTER TABLE branche_entreprise CHANGE id_branche ID_BRANCHE INT AUTO_INCREMENT NOT NULL, CHANGE localisation_branche LOCALISATION_BRANCHE TEXT DEFAULT NULL, CHANGE email_branche EMAIL_BRANCHE TEXT DEFAULT NULL, CHANGE contact_branche CONTACT_BRANCHE VARCHAR(15) DEFAULT NULL, CHANGE nombre_employe NOMBRE_EMPLOYE INT DEFAULT NULL, CHANGE responsable_branche RESPONSABLE_BRANCHE TEXT DEFAULT NULL, CHANGE ID_ENTREPRISE ID_ENTREPRISE INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL');
        $this->addSql('DROP INDEX idx_1c807087f6170f81 ON branche_entreprise');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_21 ON branche_entreprise (ID_UTILISATEUR)');
        $this->addSql('DROP INDEX idx_1c807087843f785 ON branche_entreprise');
        $this->addSql('CREATE INDEX FK_BRANCHE ON branche_entreprise (ID_ENTREPRISE)');
        $this->addSql('ALTER TABLE branche_entreprise ADD CONSTRAINT FK_1C807087843F785 FOREIGN KEY (ID_ENTREPRISE) REFERENCES entreprise (ID_ENTREPRISE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE branche_entreprise ADD CONSTRAINT FK_1C807087F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_E33BD3B8F6170F81');
        $this->addSql('ALTER TABLE candidature CHANGE id_candidature ID_CANDIDATURE INT AUTO_INCREMENT NOT NULL, CHANGE date_candidature DATE_CANDIDATURE DATE DEFAULT NULL, CHANGE statut_candidature STATUT_CANDIDATURE VARCHAR(255) DEFAULT NULL, CHANGE cv CV BLOB DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL');
        $this->addSql('DROP INDEX idx_e33bd3b8f6170f81 ON candidature');
        $this->addSql('CREATE INDEX FK_CANDIDATURE_UTILISATEUR ON candidature (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B8F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire_publication DROP FOREIGN KEY FK_423CD66B44370B4B');
        $this->addSql('ALTER TABLE commentaire_publication DROP FOREIGN KEY FK_423CD66BF6170F81');
        $this->addSql('ALTER TABLE commentaire_publication DROP FOREIGN KEY FK_423CD66B73C208DE');
        $this->addSql('ALTER TABLE commentaire_publication CHANGE id_commentaire ID_COMMENTAIRE INT AUTO_INCREMENT NOT NULL, CHANGE contenu CONTENU TEXT NOT NULL, CHANGE date_commentaire DATE_COMMENTAIRE DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE ID_PUBLICATION ID_PUBLICATION INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL');
        $this->addSql('DROP INDEX idx_423cd66b44370b4b ON commentaire_publication');
        $this->addSql('CREATE INDEX FK_COMMENTAIRE_PUBLICATION ON commentaire_publication (ID_PUBLICATION)');
        $this->addSql('DROP INDEX idx_423cd66bf6170f81 ON commentaire_publication');
        $this->addSql('CREATE INDEX FK_COMMENTAIRE_UTILISATEUR ON commentaire_publication (ID_UTILISATEUR)');
        $this->addSql('DROP INDEX idx_423cd66b73c208de ON commentaire_publication');
        $this->addSql('CREATE INDEX IDX_REPONSE ON commentaire_publication (ID_REPONSE)');
        $this->addSql('ALTER TABLE commentaire_publication ADD CONSTRAINT FK_423CD66B44370B4B FOREIGN KEY (ID_PUBLICATION) REFERENCES publication (ID_PUBLICATION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire_publication ADD CONSTRAINT FK_423CD66BF6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire_publication ADD CONSTRAINT FK_423CD66B73C208DE FOREIGN KEY (ID_REPONSE) REFERENCES commentaire_publication (ID_COMMENTAIRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department_entreprise DROP FOREIGN KEY FK_9F10F68C843F785');
        $this->addSql('ALTER TABLE department_entreprise CHANGE id_departement ID_DEPARTEMENT INT AUTO_INCREMENT NOT NULL, CHANGE nom_departement NOM_DEPARTEMENT TEXT DEFAULT NULL, CHANGE description_departement DESCRIPTION_DEPARTEMENT TEXT DEFAULT NULL, CHANGE responsable_departement RESPONSABLE_DEPARTEMENT TEXT DEFAULT NULL, CHANGE nbr_employe_departement NBR_EMPLOYE_DEPARTEMENT INT DEFAULT NULL, CHANGE ID_ENTREPRISE ID_ENTREPRISE INT NOT NULL');
        $this->addSql('DROP INDEX idx_9f10f68c843f785 ON department_entreprise');
        $this->addSql('CREATE INDEX FK_CONTENI ON department_entreprise (ID_ENTREPRISE)');
        $this->addSql('ALTER TABLE department_entreprise ADD CONSTRAINT FK_9F10F68C843F785 FOREIGN KEY (ID_ENTREPRISE) REFERENCES entreprise (ID_ENTREPRISE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE entreprise CHANGE id_entreprise ID_ENTREPRISE INT AUTO_INCREMENT NOT NULL, CHANGE nom_entreprise NOM_ENTREPRISE TEXT DEFAULT NULL, CHANGE description_entreprise DESCRIPTION_ENTREPRISE TEXT DEFAULT NULL, CHANGE logo_entreprise LOGO_ENTREPRISE LONGBLOB DEFAULT NULL, CHANGE url_entreprise URL_ENTREPRISE TEXT DEFAULT NULL, CHANGE secteur_entreprise SECTEUR_ENTREPRISE TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE hebergement DROP FOREIGN KEY FK_4852DD9C5458B0B4');
        $this->addSql('ALTER TABLE hebergement CHANGE id_hebergement ID_HEBERGEMENT INT AUTO_INCREMENT NOT NULL, CHANGE nom_hebergement NOM_HEBERGEMENT VARCHAR(255) DEFAULT NULL, CHANGE adresse_hebergement ADRESSE_HEBERGEMENT VARCHAR(255) DEFAULT NULL, CHANGE type_hebergement TYPE_HEBERGEMENT VARCHAR(255) DEFAULT NULL, CHANGE description_hebergement DESCRIPTION_HEBERGEMENT TEXT DEFAULT NULL, CHANGE nbr_nuite_hebergement NBR_NUITE_HEBERGEMENT INT DEFAULT NULL, CHANGE disponibilite_hebergement DISPONIBILITE_HEBERGEMENT TINYINT(1) DEFAULT NULL, CHANGE localisation_hebergement LOCALISATION_HEBERGEMENT VARCHAR(255) DEFAULT NULL, CHANGE prix_hebergement PRIX_HEBERGEMENT NUMERIC(10, 2) DEFAULT NULL, CHANGE ID_PARTENARIAT ID_PARTENARIAT INT NOT NULL');
        $this->addSql('DROP INDEX idx_4852dd9c5458b0b4 ON hebergement');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_14 ON hebergement (ID_PARTENARIAT)');
        $this->addSql('ALTER TABLE hebergement ADD CONSTRAINT FK_4852DD9C5458B0B4 FOREIGN KEY (ID_PARTENARIAT) REFERENCES partenariat (ID_PARTENARIAT) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE historique_candidature DROP FOREIGN KEY FK_3A95DDDE830BF8A');
        $this->addSql('ALTER TABLE historique_candidature CHANGE id_historique ID_HISTORIQUE INT AUTO_INCREMENT NOT NULL, CHANGE statut_avant STATUT_AVANT VARCHAR(255) DEFAULT NULL, CHANGE statut_apres STATUT_APRES VARCHAR(255) DEFAULT NULL, CHANGE date_modification DATE_MODIFICATION DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE ID_CANDIDATURE ID_CANDIDATURE INT NOT NULL');
        $this->addSql('DROP INDEX idx_3a95ddde830bf8a ON historique_candidature');
        $this->addSql('CREATE INDEX FK_HISTORIQUE_CANDIDATURE ON historique_candidature (ID_CANDIDATURE)');
        $this->addSql('ALTER TABLE historique_candidature ADD CONSTRAINT FK_3A95DDDE830BF8A FOREIGN KEY (ID_CANDIDATURE) REFERENCES candidature (ID_CANDIDATURE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_CF1D3C34F6170F81');
        $this->addSql('ALTER TABLE interview DROP FOREIGN KEY FK_CF1D3C34809C5E25');
        $this->addSql('ALTER TABLE interview CHANGE id_interview ID_INTERVIEW INT AUTO_INCREMENT NOT NULL, CHANGE titre_offre titre_offre TEXT DEFAULT NULL, CHANGE nom_utilisateur nom_utilisateur VARCHAR(100) DEFAULT NULL, CHANGE prenom_utilisateur prenom_utilisateur VARCHAR(100) DEFAULT NULL, CHANGE date_interview DATE_INTERVIEW DATE DEFAULT NULL, CHANGE type_interview TYPE_INTERVIEW VARCHAR(255) DEFAULT NULL, CHANGE lien_meet lien_Meet VARCHAR(255) DEFAULT NULL, CHANGE localisation localisation VARCHAR(255) DEFAULT NULL, CHANGE time_interview time_Interview TIME NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_OFFRE ID_OFFRE INT NOT NULL');
        $this->addSql('DROP INDEX idx_cf1d3c34809c5e25 ON interview');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_20 ON interview (ID_OFFRE)');
        $this->addSql('DROP INDEX idx_cf1d3c34f6170f81 ON interview');
        $this->addSql('CREATE INDEX FK_INTERVIEW_UTILISATEUR ON interview (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_CF1D3C34F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interview ADD CONSTRAINT FK_CF1D3C34809C5E25 FOREIGN KEY (ID_OFFRE) REFERENCES offre (ID_OFFRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offre DROP FOREIGN KEY FK_AF86866FF6170F81');
        $this->addSql('ALTER TABLE offre DROP FOREIGN KEY FK_AF86866F843F785');
        $this->addSql('ALTER TABLE offre CHANGE id_offre ID_OFFRE INT AUTO_INCREMENT NOT NULL, CHANGE titre_offre TITRE_OFFRE TEXT DEFAULT NULL, CHANGE description_offre DESCRIPTION_OFFRE TEXT DEFAULT NULL, CHANGE salaire_offre SALAIRE_OFFRE DOUBLE PRECISION DEFAULT NULL, CHANGE localisation_offre LOCALISATION_OFFRE TEXT DEFAULT NULL, CHANGE email_rh EMAIL_RH TEXT NOT NULL, CHANGE type_contrat TYPE_CONTRAT TEXT NOT NULL, CHANGE date_limite DATE_LIMITE DATE DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_ENTREPRISE ID_ENTREPRISE INT NOT NULL');
        $this->addSql('DROP INDEX idx_af86866f843f785 ON offre');
        $this->addSql('CREATE INDEX FK_offre_entreprise ON offre (ID_ENTREPRISE)');
        $this->addSql('DROP INDEX idx_af86866ff6170f81 ON offre');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_13 ON offre (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE offre ADD CONSTRAINT FK_AF86866FF6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offre ADD CONSTRAINT FK_AF86866F843F785 FOREIGN KEY (ID_ENTREPRISE) REFERENCES entreprise (ID_ENTREPRISE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE partenariat DROP FOREIGN KEY FK_BF53DC864E1D27AD');
        $this->addSql('ALTER TABLE partenariat CHANGE id_partenariat ID_PARTENARIAT INT AUTO_INCREMENT NOT NULL, CHANGE nom_partenariat NOM_PARTENARIAT VARCHAR(255) DEFAULT NULL, CHANGE adresse_partenariat ADRESSE_PARTENARIAT VARCHAR(255) DEFAULT NULL, CHANGE num_tel_partenariat NUM_TEL_PARTENARIAT VARCHAR(15) DEFAULT NULL, CHANGE ID_BRANCHE ID_BRANCHE INT NOT NULL');
        $this->addSql('DROP INDEX idx_bf53dc864e1d27ad ON partenariat');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_23 ON partenariat (ID_BRANCHE)');
        $this->addSql('ALTER TABLE partenariat ADD CONSTRAINT FK_BF53DC864E1D27AD FOREIGN KEY (ID_BRANCHE) REFERENCES branche_entreprise (ID_BRANCHE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA9809C5E25');
        $this->addSql('ALTER TABLE projet CHANGE id_projet ID_PROJET INT AUTO_INCREMENT NOT NULL, CHANGE titre_projet TITRE_PROJET TEXT DEFAULT NULL, CHANGE description_projet DESCRIPTION_PROJET TEXT DEFAULT NULL, CHANGE date_debut DATE_DEBUT DATE DEFAULT NULL, CHANGE date_fin DATE_FIN DATE DEFAULT NULL, CHANGE ID_OFFRE ID_OFFRE INT NOT NULL');
        $this->addSql('DROP INDEX idx_50159ca9809c5e25 ON projet');
        $this->addSql('CREATE INDEX FK_PROPOSER ON projet (ID_OFFRE)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA9809C5E25 FOREIGN KEY (ID_OFFRE) REFERENCES offre (ID_OFFRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publication DROP FOREIGN KEY FK_AF3C6779F6170F81');
        $this->addSql('ALTER TABLE publication CHANGE id_publication ID_PUBLICATION INT AUTO_INCREMENT NOT NULL, CHANGE contenu CONTENU TEXT NOT NULL, CHANGE date_publication DATE_PUBLICATION DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL');
        $this->addSql('DROP INDEX idx_af3c6779f6170f81 ON publication');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_17 ON publication (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_AF3C6779F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY FK_CE606404F6170F81');
        $this->addSql('ALTER TABLE reclamation CHANGE id_reclamation ID_RECLAMATION INT AUTO_INCREMENT NOT NULL, CHANGE date_reclamation DATE_RECLAMATION DATE DEFAULT NULL, CHANGE texte_reclamation TEXTE_RECLAMATION TEXT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL');
        $this->addSql('DROP INDEX idx_ce606404f6170f81 ON reclamation');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_11 ON reclamation (ID_UTILISATEUR)');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE606404F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE repondre DROP FOREIGN KEY FK_F66FAAF48CFB048E');
        $this->addSql('ALTER TABLE repondre DROP FOREIGN KEY FK_F66FAAF4F6170F81');
        $this->addSql('DROP INDEX idx_f66faaf4f6170f81 ON repondre');
        $this->addSql('CREATE INDEX FK_REPONDRE3 ON repondre (ID_UTILISATEUR)');
        $this->addSql('DROP INDEX idx_f66faaf48cfb048e ON repondre');
        $this->addSql('CREATE INDEX FK_REPONDRE2 ON repondre (ID_COMMENTAIRE)');
        $this->addSql('ALTER TABLE repondre ADD CONSTRAINT FK_F66FAAF48CFB048E FOREIGN KEY (ID_COMMENTAIRE) REFERENCES commentaire_publication (ID_COMMENTAIRE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE repondre ADD CONSTRAINT FK_F66FAAF4F6170F81 FOREIGN KEY (ID_UTILISATEUR) REFERENCES utilisateur (ID_UTILISATEUR) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse_commentaire_publication CHANGE id_reponse_commentaire ID_REPONSE_COMMENTAIRE INT AUTO_INCREMENT NOT NULL, CHANGE contenu_reponse_commentaire_publication CONTENU_REPONSE_COMMENTAIRE_PUBLICATION TEXT DEFAULT NULL, CHANGE date_reponse_commentaire_publication DATE_REPONSE_COMMENTAIRE_PUBLICATION DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE reponse_reclamation DROP FOREIGN KEY FK_C7CB5101256B0836');
        $this->addSql('ALTER TABLE reponse_reclamation CHANGE id_reponse ID_REPONSE INT AUTO_INCREMENT NOT NULL, CHANGE date_reponse DATE_REPONSE DATE DEFAULT NULL, CHANGE texte_reponse TEXTE_REPONSE TEXT DEFAULT NULL, CHANGE ID_RECLAMATION ID_RECLAMATION INT NOT NULL');
        $this->addSql('DROP INDEX idx_c7cb5101256b0836 ON reponse_reclamation');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_18 ON reponse_reclamation (ID_RECLAMATION)');
        $this->addSql('ALTER TABLE reponse_reclamation ADD CONSTRAINT FK_C7CB5101256B0836 FOREIGN KEY (ID_RECLAMATION) REFERENCES reclamation (ID_RECLAMATION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE test_technique DROP FOREIGN KEY FK_55A60F8B9547CAD3');
        $this->addSql('ALTER TABLE test_technique CHANGE id_test_technique ID_TEST_TECHNIQUE INT AUTO_INCREMENT NOT NULL, CHANGE titre_test_technique TITRE_TEST_TECHNIQUE VARCHAR(255) DEFAULT NULL, CHANGE description_test_technique DESCRIPTION_TEST_TECHNIQUE VARCHAR(255) DEFAULT NULL, CHANGE duree_test_technique DUREE_TEST_TECHNIQUE INT DEFAULT NULL, CHANGE statut_test_technique STATUT_TEST_TECHNIQUE VARCHAR(255) DEFAULT \'EN_ATTENTE\', CHANGE date_creation_test_technique DATE_CREATION_TEST_TECHNIQUE DATETIME DEFAULT NULL, CHANGE questions questions LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE ID_INTERVIEW ID_INTERVIEW INT NOT NULL');
        $this->addSql('DROP INDEX idx_55a60f8b9547cad3 ON test_technique');
        $this->addSql('CREATE INDEX FK_ASSOCIATION_16 ON test_technique (ID_INTERVIEW)');
        $this->addSql('ALTER TABLE test_technique ADD CONSTRAINT FK_55A60F8B9547CAD3 FOREIGN KEY (ID_INTERVIEW) REFERENCES interview (ID_INTERVIEW) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur CHANGE id_utilisateur ID_UTILISATEUR INT AUTO_INCREMENT NOT NULL, CHANGE nom_utilisateur NOM_UTILISATEUR VARCHAR(100) DEFAULT NULL, CHANGE prenom_utilisateur PRENOM_UTILISATEUR VARCHAR(100) DEFAULT NULL, CHANGE age_utilisateur AGE_UTILISATEUR INT DEFAULT NULL, CHANGE email_utilisateur EMAIL_UTILISATEUR VARCHAR(255) DEFAULT NULL, CHANGE mot_de_passe_utilisateur MOT_DE_PASSE_UTILISATEUR VARCHAR(255) DEFAULT NULL, CHANGE role ROLE VARCHAR(255) DEFAULT NULL, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL, CHANGE profile_picture_url profile_picture_url VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX EMAIL_UTILISATEUR ON utilisateur (EMAIL_UTILISATEUR)');
    }
}
